film_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from films import urls as films_urls
from rest_api import urls as rest_urls
from get_api import urls as get_api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(films_urls, namespace='films')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/', include(rest_urls, namespace='rest_api')),
    url(r'^get/v1/', include(get_api, namespace='get_api')),

]

films/urls.py
from django.conf.urls import url

from .views import index, films, film, genres, genre

urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^genres/$', genres, name='genres'),
    url(r'^genres/(?P<genre_pk>[0-9]+)/', genre, name='genre'),

    url(r'^films/$', films, name='films'),
    url(r'^films/(?P<film_pk>[0-9]+)/', film, name='film'),
]

get_api/urls.py
from django.conf.urls import url

from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

rest_api/urls.py
from rest_framework import routers, serializers, viewsets
from .views import FilmViewSet, GenreViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'film', FilmViewSet, 'film-list')
router.register(r'genre', GenreViewSet, 'genre-detail')

urlpatterns = router.urls

films/models.py
from django.db import models


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return "Genre: {}".format(self.name)


class Film(models.Model):
    name = models.CharField(max_length=100)
    genre = models.ForeignKey('Genre', related_name='film', blank=True, null=True)

    def __str__(self):
        return "Film name: {}".format(self.name)

get_api/models.py
from django.db import models

# Create your models here.

rest_api/models.py
from django.db import models

# Create your models here.

films/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Film, Genre


class PlaceholderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PlaceholderForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                if type(field.widget) in (forms.TextInput, ):
                    field.widget.attrs.update(
                        {'placeholder': field.label, 'class': 'span10'}
                    )
                if type(field.widget) in (forms.Select, ):
                    field.widget.attrs.update({'class': 'span10'})
                    field.empty_label = field.label

    def as_p(self):
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s%(help_text)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True
        )


class GenreForm(PlaceholderForm):
    class Meta:
        model = Genre
        fields = ['name']


class FilmForm(PlaceholderForm):
    class Meta:
        model = Film
        fields = ['name', 'genre']

films/views.py
from django.shortcuts import render
from django.db import transaction
from django.http import Http404
from .models import Genre, Film
from .forms import GenreForm, FilmForm
# Create your views here.


def index(request):
    return render(request, 'films/index.html')


def films(request):
    films_form = FilmForm()

    if request.method == 'POST':
        previous_film_form = FilmForm(request.POST)
        if previous_film_form.is_valid():
            with transaction.atomic():
                previous_film_form.save()
            films_form = previous_film_form
    return render(request, 'films/films.html', {
        'films': Film.objects.all(),
        'form': films_form,
    })


def film(request, film_pk):
    try:
        film_form = FilmForm(instance=Film.objects.get(pk=film_pk))
    except Film.DoesNotExist:
        raise Http404('There in no such film!')

    if request.method == 'POST':
        instance = Film.objects.get(pk=film_pk)
        previous_film_form = FilmForm(request.POST, instance=instance)
        if previous_film_form.is_valid():
            with transaction.atomic():
                previous_film_form.save()
            film_form = previous_film_form

    return render(request, 'films/film.html', {
        'form': film_form,
        'genres': Genre.objects.all().filter(film=film_pk),
    })


def genres(request):
    genres_form = GenreForm()

    if request.method == 'POST':
        previous_genres_form = GenreForm(request.POST)
        if previous_genres_form.is_valid():
            with transaction.atomic():
                previous_genres_form.save()
        else:
            genres_form = previous_genres_form

    return render(request, 'films/genres.html', {
        'genres': Genre.objects.all(),
        'form': genres_form,
    })


def genre(request, genre_pk):
    try:
        genre_form = GenreForm(instance=Genre.objects.get(pk=genre_pk))
    except Genre.DoesNotExist:
        raise Http404('There in no such genre theme!')

    if request.method == 'POST':
        instance = Genre.objects.get(pk=genre_pk)
        previous_genre_form = GenreForm(request.POST, instance=instance)
        if previous_genre_form.is_valid():
            with transaction.atomic():
                previous_genre_form.save()
            genre_form = previous_genre_form

    return render(request, 'films/genre.html', {
        'form': genre_form,
    })

get_api/views.py
import requests
import json
import time

from django.shortcuts import render


def index(request):

    context = {}

    if request.method == 'POST':
        start_time_main = time.time()
        r_index = requests.get("http://127.0.0.1:8000/api/v1/")
        r_films = requests.get("http://127.0.0.1:8000/api/v1/film/")
        r_genres = requests.get("http://127.0.0.1:8000/api/v1/genre/")
        api_request_time = time.time() - start_time_main

        if r_index.status_code == 200 and r_films.status_code == 200 \
                and r_genres.status_code == 200:

            _result = "Successfully connected to local API!"
            index_result = json.loads(r_index.content.decode('utf-8'))
            films_result = json.loads(r_films.content.decode('utf-8'))
            genres_result = json.loads(r_genres.content.decode('utf-8'))

            context = {
                'index_result': index_result,
                'films_result': films_result,
                'genres_result': genres_result,
            }
        else:
            _result = "Something went wrong with connection to local API"

        context.update({
            "connection_result": _result,
            'api_request_time': api_request_time,
        })

    return render(request, 'get_api/index.html', context)

rest_api/views.py
from rest_framework import viewsets
from films.models import Film, Genre
from .serializers import FilmSerializer, GenreSerializer
# Create your views here.


class FilmViewSet(viewsets.ModelViewSet):
    queryset = Film.objects.all()
    serializer_class = FilmSerializer


class GenreViewSet(viewsets.ModelViewSet):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer

films/templates/films/_base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'custom.css' %}" />

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li><a href="{% url 'films:index' %}">Home</a></li>
              <li><a href="{% url 'films:films' %}">Films</a></li>
              <li><a href="{% url 'films:genres' %}">Genres</a></li>
              <li><a href="{% url 'rest_api:api-root' %}">REST API</a></li>
              <li><a href="{% url 'get_api:index' %}">Get from api</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                {% block content %}{% endblock content %}
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>

</body>
</html>

films/templates/films/film.html
{% extends 'films/_base.html' %}

{% block title %}Film API: film {{ film.name }}{% endblock title %}

{% block content %}

    <h1>Film</h1><br>

    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
            {{ field.label_tag }}<br>
            {{ field }}<br>
            {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <br>
    <h3>Genres for films:</h3>
    {% if genres %}
        {% for genre in genres %}
            <a href="{% url 'films:genre' genre.pk %}">{{ genre }}</a></br>
        {% endfor %}
    {% else %}
        Sorry, No Genres!
    {% endif %}
{% endblock content %}

films/templates/films/films.html
{% extends 'films/_base.html' %}

{% block title %}Film API: film{% endblock title %}

{% block content %}
    <h1>Films page</h1>

    <br></b><h3>Films list:</h3>
    {% for film in films %}
        <p><a href="{% url 'films:film' film.pk %}">{{ film }}</a></p>
    {% endfor %}

    <br><h3>New film:</h3>
    <form action="{% url 'films:films' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}

films/templates/films/genre.html
{% extends 'films/_base.html' %}

{% block content %}

    <h1>Film genre</h1><br>

    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
            {{ field.label_tag }}<br>
            {{ field }}<br>
            {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock content %}

films/templates/films/genres.html
{% extends 'films/_base.html' %}

{% block title %}Django API: genres{% endblock title %}

{% block content %}
    <h1>Film genres</h1>

    <br></b><h3>Genres:</h3>
    {% for genre in genres %}
        <p><a href="{% url 'films:genre' genre.pk %}">{{ genre }}</a></p>
    {% endfor %}

    <br><h3>New genre:</h3>
    <form action="{% url 'films:genres' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

films/templates/films/index.html
{% extends 'films/_base.html' %}

{% block title %}Films API{% endblock title %}

{% block content %}
    <h1>My rest api for films</h1>

    <p>Checkout films and genres here.</p>
{% endblock content %}

get_api/templates/get_api/index.html
{% extends 'films/_base.html' %}

{% block title %}Get from local API{% endblock title %}

{% block content %}
    <h1>Get data from local API</h1>

    <form action="{% url 'get_api:index' %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Connect to local API">
    </form>

    {% if connection_result %}
        <p><p><em>{{ connection_result }}</em></p></p>
        <p>Connection takes: {{ api_request_time }} seconds.</p>
    {% endif %}

    {% if index_result %}
        <strong>Index:</strong>
        <ul>
        {% for k, v in index_result.items %}
            <li><a href="{{ v }}">{{ k }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}

    {% if films_result %}
        <strong>Films:</strong>
        <ul>
        {% for film in films_result %}
            <li>{{ film.name }}</li>
        {% endfor %}
        </ul>
    {% endif %}

    {% if genres_result %}
        <strong>Genres:</strong>
        <ul>
        {% for genre in genres_result %}
            <li>{{ genre.name }}</li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock content %}